name: my_profile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  auto_route: ^8.0.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  crypto: ^3.0.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_svg: ^2.0.7

  #state data_management
  flutter_bloc: ^8.1.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

